# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
environment:
  matrix:
  - nodejs_version: 8
  - nodejs_version: 10
  - nodejs_version: 12

install:
  - ps: Install-Product node $env:nodejs_version

  - cd ..
  - git clone https://github.com/apache/cordova-android --depth 10
  - git clone https://github.com/apache/cordova-ios --depth 10
  - git clone https://github.com/apache/cordova-windows --depth 10
  - git clone https://github.com/apache/cordova-browser --depth 10
  - cd cordova-js
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - npm test
